### ISSUE TITLE
Start timer from preset time

### ISSUE THREAD

**Issue by haaris94** [hukusuke1007/stop_watch_timer#1]
Hi! Is there a way to start the timer from a given time. Instead of starting from 0 minutes 0 hrs, the timer should start from a given hour, minutes, and sec. For example, start from 2 hrs, 36 mins and 46 secs like this.

**Comment by hukusuke1007** [comment]
Thank you for question. Sorry, can not set preset time.

OK!  I will added parameter for preset time.

**Comment by haaris94** [comment]
Thank you for the response and thank you for implementing the feature.

**Comment by hukusuke1007** [comment]
I finished to add preset time feature.
Please check latest version.
https://pub.dev/packages/stop_watch_timer

**Comment by hukusuke1007** [comment]
@namaye Please check latest and close this issue.

**Comment by haaris94** [comment]
Sorry! was working on other projects. I'll get to that project in a couple of days, So I'll close this issue for now. If needed I'll reopen this. Anyway, thanks for implementing this feature
