### ISSUE TITLE
Cannot stop stopWatch

### ISSUE THREAD

**Issue by gruessung** [hukusuke1007/stop_watch_timer#10]
I use the following commands to start and stop the stopwatch:
 
`    _stopWatchTimer.onExecute.add(StopWatchExecute.start);
`
`     _stopWatchTimer.onExecute.add(StopWatchExecute.stop);
`
Unfortunately, the second command does not work, the stopwatch continues to run.

**Comment by hukusuke1007** [comment]
Please show me your flutter environment and source code.
