### ISSUE TITLE
How Can I make background Timer ?

### ISSUE THREAD

**Issue by tonmooy** [hukusuke1007/stop_watch_timer#12]
Hello Sir, 
I want to make, Background Timer If i start timer from a page , when i close The page ,it without disposing

value will print in console log
but if i go back to the page Stream Builder start from beginnings,

But console log print old value as well, 

Now, how can i get the old value in stream builder?

**Comment by hukusuke1007** [comment]
I might not have understand correctly what you want to do...
I suggest the following design.

![sprint_watch_timer_design](https://user-images.githubusercontent.com/29278033/120804505-b26df080-c57f-11eb-9aba-caacdc1ece72.png)

"TimerStateNotifier" has  old value of SprintWatchTimer.
