### ISSUE TITLE
Background timer doesn't work

### ISSUE THREAD

**Issue by hanyska** [hukusuke1007/stop_watch_timer#16]
When I moved app to background the timer stopped

**Comment by hukusuke1007** [comment]
@hanyska Really? Please show me your source code and your environments.

**Comment by mirkancal** [comment]
What's the best way to use it on background?

So far, I didn't see iOS killed my app in background, so I can see the correct timer after a second when I put my app in foreground. However, I'm also listening the seconds stream to update live_activities, it doesn't update when it's in background. What's the best way to run stop_watch_timer in background?
