### ISSUE TITLE
Add support for parsing hours

### ISSUE THREAD

**Issue by mdev88** [hukusuke1007/stop_watch_timer#2]
Hey, I love your plugin!

The only thing stopping me from actually using it is that it does not support hours... which I need for my project :(

I am writing a time tracker destkop app that accumulates the time spent on different tasks on a monthly basis, so as you can imagine, the counter crosses the hour barrier very quickly...

Do you think it's possible to add this functionality in the near future?

Thanks!

**Comment by hukusuke1007** [comment]
Thank you for comment. 
Yes,  I will support to parsing hours feature in the near futures.
When i finish to added it, i'll contact you later.

**Comment by mdev88** [comment]
Excellent! In the meantime I have found a workaround by parsing the raw time myself but having the convenience methods like the ones for seconds and minutes would be even better.

Thanks again!

**Comment by hukusuke1007** [comment]
I finished it. Please check latest version.
https://github.com/hukusuke1007/stop_watch_timer/pull/4

**Comment by mdev88** [comment]
Looks good to me :)
Thanks!
