### ISSUE TITLE
Preset Time

### ISSUE THREAD

**Issue by naaera** [hukusuke1007/stop_watch_timer#24]
Hello,

Is there a way to force presettime countdown to 0 and set a new preset time ?.

I've tried using clearPresetTime() function, but if i start the stopwatch countdown the stopwatch not start from the new preset time . example : remaining time is 5second and then i call clearPresetTime(), and then i set new preset time 20second and start the countdown again, but the timer started from 15second not 20second
![Screenshot_20220519_101150](https://user-images.githubusercontent.com/45729061/169196631-e092d0c1-370b-4071-b20f-0bb0bed34b6d.png)
![Screenshot_20220519_101252](https://user-images.githubusercontent.com/45729061/169196645-8044d52d-0c90-4e52-b9de-505faaf51a51.png)

Thank you in advance

**Comment by ekremkmz** [comment]
#27 I need this feature too
