### ISSUE TITLE
[feature] Make StopWatchMode not final.

### ISSUE THREAD

**Issue by bastienJS** [hukusuke1007/stop_watch_timer#29]
I have this use case:

I create a stopwatch with counting up because time passes by and the user is NOT exercising at the moment.
When the user starts with exercising the stopwatch should count down if it is a timed based set ;-)

Therefore I need a setter for the StopWatchMode or make it not final.
I just need to change very often during user interaction.

**Comment by duncan2235** [comment]
I need a getter for the StopWatchMode
