### ISSUE TITLE
setPresetSecondTime() and setPresetTime() not working as expected when used repeatedly

### ISSUE THREAD

**Issue by CarlosCabarcos** [hukusuke1007/stop_watch_timer#39]
Good evening,

I'm not sure if I have missunderstood something about how this should work, but when using them several times in a row, they are not acting as you would expect. I'll explain it:

I have implemented a Pause function for the stop watch.

If I call:

```
void resetToZero(){
  _stopWatchTimer.onStopTimer();
  _stopWatchTimer.onResetTimer();
  _stopWatchTimer.onStartTimer();
}
```
The timer properly resets to 0 and continues working. I can call it as many times as I want, and it will always work properly.
if I call:

```
void resetToZeroVersionTwo(){
  _stopWatchTimer.onStopTimer();
  _stopWatchTimer.onResetTimer();
  _stopWatchTimer.setPresetSecondTime(0);
  _stopWatchTimer.onStartTimer();
}
```
The exact same thing happens. The timer gets reset properly.

However, if I call this: 

```
void resetToTen(){
  _stopWatchTimer.onStopTimer();
  _stopWatchTimer.onResetTimer();
  _stopWatchTimer.setPresetSecondTime(10);
  _stopWatchTimer.onStartTimer();
}
```

The first time I call it, it works correctly. The timer goes back to 10. But, if I call it more times, it does not work as expected. Instead of reseting to ten every time, the next times, it resets to 10 + the time at which I pressed the reset button. The same happens if I use the "setPresetTime" function instead of the "seconds" version.

Either I'm not understanding something about how these functions should work, or something is bugged. Could someone help me out?

Thank you.

**Comment by ZippyRainbow** [comment]
@CarlosCabarcos I had a similar issue.

But i noticed with the setPresentSecondTime and setPresentTime, there is a optional "add" variable which defaults to true. If I set it to false it corrected my result.

So this worked for me.
```
void resetToTen(){
  _stopWatchTimer.onStopTimer();
  _stopWatchTimer.onResetTimer();
  _stopWatchTimer.setPresetSecondTime(10, add: false);
  _stopWatchTimer.onStartTimer();
}
```
