### ISSUE TITLE
setStartTime Function

### ISSUE THREAD

**Issue by ZippyRainbow** [hukusuke1007/stop_watch_timer#41]
For me, I wanted to store the Start DateTime and use this to show the stopwatch from this time. So I can exit out of the App, and then return to the same start time, or show the same start time on multiple logins of the app.

Thought this might be useful for others.

  ```
//Set the start time to be a particular date and time.
  void setStartTime(DateTime startTime) {    
    _startTime = startTime.millisecondsSinceEpoch;    
  }
```

**Comment by hukusuke1007** [comment]
Was presetTime not valid?
